name: Infrastructure Baseline
on:
  push:
    branches:
      - master
    paths:
      - infra/**

env:
  GCP_ARTIFACT_REPO_NAME: ${{secrets.GCP_ARTIFACT_REPO_NAME}}
  GCP_K8S_CLUSTER_NAME: ${{ secrets.GCP_K8S_CLUSTER_NAME }}
  GCP_K8S_PROXY_NAME: ${{ secrets.GCP_K8S_PROXY_NAME }}
  GCP_K8S_PROXY_PORT: ${{ secrets.GCP_K8S_PROXY_PORT }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  GCP_ZONE: ${{ secrets.GCP_ZONE}}
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

jobs:
  infrastructure-baseline:
    name: Infrastructure Baseline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Get Yarn Cache Directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Set up Yarn Cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Configure GCP Auth
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Set up Pulumi
        uses: pulumi/setup-pulumi@v2
        with:
          pulumi-version: 3.22.0

      - name: Pulumi Up!
        working-directory: infra
        run: |
          yarn
          pulumi stack select prod
          pulumi config set 'gcp:project' "${GCP_PROJECT_ID}"
          pulumi config set 'gcp:region' "${GCP_REGION}"
          pulumi config set 'gcp:zone' "${GCP_ZONE}"
          pulumi up --yes --non-interactive
